GET https://localhost:44366/api/authors HTTP/1.1

###
PUT https://localhost:44366/api/authors/1fccccf5-cfac-4909-84d5-03360ffaf500 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jean",
    "lastName": "Bourne",    
    "age": 20,
    "monthlyPaymentAmount":120000000
}
###
