using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Threading;

namespace AspireOpenTelemetry.Server.Tariffs;

public static class TariffTelemetry
{
    public const string ActivitySourceName = "AspireOpenTelemetry.Server.Tariffs";
    public const string MeterName = "AspireOpenTelemetry.Server.Tariffs";

    public static readonly ActivitySource ActivitySource = new(ActivitySourceName);

    private static readonly Meter Meter = new(MeterName);

    public static readonly Counter<long> BatchGenerated = Meter.CreateCounter<long>(
        "tariff.batch.generated",
        unit: "{batch}",
        description: "Number of absurd tariff batches generated by the ministry.");

    public static readonly Counter<long> CountryQuotesGenerated = Meter.CreateCounter<long>(
        "tariff.country.generated",
        unit: "{country}",
        description: "Number of country tariff quotes generated.");

    public static readonly Counter<long> InspectionRequests = Meter.CreateCounter<long>(
        "tariff.inspect.requests",
        unit: "{request}",
        description: "Number of detailed tariff inspections requested.");

    public static readonly Counter<long> AuditRuns = Meter.CreateCounter<long>(
        "tariff.audit.runs",
        unit: "{audit}",
        description: "Number of emergency tariff audits executed.");

    public static readonly Counter<long> FlaggedCountries = Meter.CreateCounter<long>(
        "tariff.audit.flagged_countries",
        unit: "{country}",
        description: "Number of countries flagged by tariff audits.");

    public static readonly Counter<long> DisputeAttempts = Meter.CreateCounter<long>(
        "tariff.dispute.attempts",
        unit: "{dispute}",
        description: "Number of staged trade disputes.");

    public static readonly Counter<long> DisputeEscalations = Meter.CreateCounter<long>(
        "tariff.dispute.escalations",
        unit: "{incident}",
        description: "Number of disputes that escalated into drama.");

    public static readonly Histogram<double> TariffPercent = Meter.CreateHistogram<double>(
        "tariff.percent",
        unit: "percent",
        description: "Observed absurd tariff percentages.");

    public static readonly Histogram<int> BatchSize = Meter.CreateHistogram<int>(
        "tariff.batch.size",
        unit: "{country}",
        description: "How many countries were included in each generated batch.");

    private static int _catalogSize;
    private static int _absurdityIndex;

    private static readonly ObservableGauge<int> CatalogSizeGauge = Meter.CreateObservableGauge(
        "tariff.catalog.size",
        () => new Measurement<int>(Volatile.Read(ref _catalogSize)),
        unit: "{country}",
        description: "Number of countries available to the tariff ministry.");

    private static readonly ObservableGauge<int> AbsurdityIndexGauge = Meter.CreateObservableGauge(
        "tariff.absurdity.index",
        () => new Measurement<int>(Volatile.Read(ref _absurdityIndex)),
        unit: "{score}",
        description: "Average absurdity score of the most recent batch.");

    public static void UpdateCatalogSize(int value)
    {
        Interlocked.Exchange(ref _catalogSize, value);
    }

    public static void UpdateAbsurdityIndex(int value)
    {
        Interlocked.Exchange(ref _absurdityIndex, value);
    }
}
