//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Soap.Client.QuizServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizFrage", Namespace="http://schemas.datacontract.org/2004/07/WCF.Soap.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class QuizFrage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AntwortenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Antworten {
            get {
                return this.AntwortenField;
            }
            set {
                if ((object.ReferenceEquals(this.AntwortenField, value) != true)) {
                    this.AntwortenField = value;
                    this.RaisePropertyChanged("Antworten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frage {
            get {
                return this.FrageField;
            }
            set {
                if ((object.ReferenceEquals(this.FrageField, value) != true)) {
                    this.FrageField = value;
                    this.RaisePropertyChanged("Frage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizResultat", Namespace="http://schemas.datacontract.org/2004/07/WCF.Soap.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class QuizResultat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntwortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RichtigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Antwort {
            get {
                return this.AntwortField;
            }
            set {
                if ((object.ReferenceEquals(this.AntwortField, value) != true)) {
                    this.AntwortField = value;
                    this.RaisePropertyChanged("Antwort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Richtig {
            get {
                return this.RichtigField;
            }
            set {
                if ((this.RichtigField.Equals(value) != true)) {
                    this.RichtigField = value;
                    this.RaisePropertyChanged("Richtig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuizServiceClient.IQuizService")]
    public interface IQuizService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizService/HoleFrage", ReplyAction="http://tempuri.org/IQuizService/HoleFrageResponse")]
        WCF.Soap.Client.QuizServiceClient.QuizFrage HoleFrage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizService/HoleFrage", ReplyAction="http://tempuri.org/IQuizService/HoleFrageResponse")]
        System.Threading.Tasks.Task<WCF.Soap.Client.QuizServiceClient.QuizFrage> HoleFrageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizService/BeantworteFrage", ReplyAction="http://tempuri.org/IQuizService/BeantworteFrageResponse")]
        WCF.Soap.Client.QuizServiceClient.QuizResultat BeantworteFrage(int frageID, int antwortIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizService/BeantworteFrage", ReplyAction="http://tempuri.org/IQuizService/BeantworteFrageResponse")]
        System.Threading.Tasks.Task<WCF.Soap.Client.QuizServiceClient.QuizResultat> BeantworteFrageAsync(int frageID, int antwortIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuizServiceChannel : WCF.Soap.Client.QuizServiceClient.IQuizService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuizServiceClient : System.ServiceModel.ClientBase<WCF.Soap.Client.QuizServiceClient.IQuizService>, WCF.Soap.Client.QuizServiceClient.IQuizService {
        
        public QuizServiceClient() {
        }
        
        public QuizServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuizServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuizServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuizServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF.Soap.Client.QuizServiceClient.QuizFrage HoleFrage() {
            return base.Channel.HoleFrage();
        }
        
        public System.Threading.Tasks.Task<WCF.Soap.Client.QuizServiceClient.QuizFrage> HoleFrageAsync() {
            return base.Channel.HoleFrageAsync();
        }
        
        public WCF.Soap.Client.QuizServiceClient.QuizResultat BeantworteFrage(int frageID, int antwortIndex) {
            return base.Channel.BeantworteFrage(frageID, antwortIndex);
        }
        
        public System.Threading.Tasks.Task<WCF.Soap.Client.QuizServiceClient.QuizResultat> BeantworteFrageAsync(int frageID, int antwortIndex) {
            return base.Channel.BeantworteFrageAsync(frageID, antwortIndex);
        }
    }
}
