# Query Books with GET
GET https://localhost:5001/graphql/?query={books{name}}

###

# Query Book by Id

GET https://localhost:5001/graphql/?query={book(id:"book1"){name reviews{comment}}}

###

# Query by POST

POST https://localhost:5001/graphql
Content-Type: application/json

{
    "query":"{book(id:\"book1\"){name reviews{comment}}}"
}


###
