//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Soap.Client.UniversityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCF.Soap.Dtos")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniversityService.IUniversityService")]
    public interface IUniversityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/GetStudents", ReplyAction="http://tempuri.org/IUniversityService/GetStudentsResponse")]
        WCF.Soap.Client.UniversityService.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/GetStudents", ReplyAction="http://tempuri.org/IUniversityService/GetStudentsResponse")]
        System.Threading.Tasks.Task<WCF.Soap.Client.UniversityService.Student[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/GetStudentById", ReplyAction="http://tempuri.org/IUniversityService/GetStudentByIdResponse")]
        WCF.Soap.Client.UniversityService.Student GetStudentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/GetStudentById", ReplyAction="http://tempuri.org/IUniversityService/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<WCF.Soap.Client.UniversityService.Student> GetStudentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/AddStudent", ReplyAction="http://tempuri.org/IUniversityService/AddStudentResponse")]
        WCF.Soap.Client.UniversityService.Student AddStudent(WCF.Soap.Client.UniversityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/AddStudent", ReplyAction="http://tempuri.org/IUniversityService/AddStudentResponse")]
        System.Threading.Tasks.Task<WCF.Soap.Client.UniversityService.Student> AddStudentAsync(WCF.Soap.Client.UniversityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/UpdateStudent", ReplyAction="http://tempuri.org/IUniversityService/UpdateStudentResponse")]
        void UpdateStudent(WCF.Soap.Client.UniversityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/UpdateStudent", ReplyAction="http://tempuri.org/IUniversityService/UpdateStudentResponse")]
        System.Threading.Tasks.Task UpdateStudentAsync(WCF.Soap.Client.UniversityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/DeleteStudent", ReplyAction="http://tempuri.org/IUniversityService/DeleteStudentResponse")]
        void DeleteStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityService/DeleteStudent", ReplyAction="http://tempuri.org/IUniversityService/DeleteStudentResponse")]
        System.Threading.Tasks.Task DeleteStudentAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniversityServiceChannel : WCF.Soap.Client.UniversityService.IUniversityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniversityServiceClient : System.ServiceModel.ClientBase<WCF.Soap.Client.UniversityService.IUniversityService>, WCF.Soap.Client.UniversityService.IUniversityService {
        
        public UniversityServiceClient() {
        }
        
        public UniversityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniversityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniversityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniversityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF.Soap.Client.UniversityService.Student[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<WCF.Soap.Client.UniversityService.Student[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public WCF.Soap.Client.UniversityService.Student GetStudentById(int id) {
            return base.Channel.GetStudentById(id);
        }
        
        public System.Threading.Tasks.Task<WCF.Soap.Client.UniversityService.Student> GetStudentByIdAsync(int id) {
            return base.Channel.GetStudentByIdAsync(id);
        }
        
        public WCF.Soap.Client.UniversityService.Student AddStudent(WCF.Soap.Client.UniversityService.Student student) {
            return base.Channel.AddStudent(student);
        }
        
        public System.Threading.Tasks.Task<WCF.Soap.Client.UniversityService.Student> AddStudentAsync(WCF.Soap.Client.UniversityService.Student student) {
            return base.Channel.AddStudentAsync(student);
        }
        
        public void UpdateStudent(WCF.Soap.Client.UniversityService.Student student) {
            base.Channel.UpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task UpdateStudentAsync(WCF.Soap.Client.UniversityService.Student student) {
            return base.Channel.UpdateStudentAsync(student);
        }
        
        public void DeleteStudent(int id) {
            base.Channel.DeleteStudent(id);
        }
        
        public System.Threading.Tasks.Task DeleteStudentAsync(int id) {
            return base.Channel.DeleteStudentAsync(id);
        }
    }
}
